#!/bin/bash
# Lists regularly used bookmarks in Rofi and opens them in the browser.

myTerm=foot
myEdit=nvim
myBrowser=brave

menu(){
    printf "1. BBC Scores & Fixtures (sc)\n"
    printf "2. Bluesky (bs)\n"
    printf "3. Hacker News (hn)\n"
    printf "4. Crimson Daggers (cd)\n"
	printf "5. Github (gh)\n"
	printf "6. Lemmy.world (lm) \n"
    printf "7. Reddit (re)\n"
    printf "8. Wikipedia (wi)\n"
}

main(){
    choice=$(menu | rofi -dmenu | cut -d. -f1)

	case $choice in
        1) $myBrowser bsky.app
            ;;
		2)
            $myBrowser www.bbc.co.uk/sport/football/scores-fixtures
            ;;
		3)
            $myBrowser https://news.ycombinator.com/news
            ;;
		4)
            $myBrowser https://crimsondaggers.com/forum/forum-10.html
            ;;
		5)
            $myBrowser github.com/bleds1
            ;;
		6)
            $myBrowser lemmy.world
            ;;
        7)
            $myBrowser reddit.com
            ;;
        8)
            $myBrowser en.wikipedia.org/wiki/Main_Page
            ;;
        esac
}

main
