#!/bin/bash
# Terminal command for search zk for Reference notes and edit on selection

zet="/home/bledley/Documents/zk/Reference/"

menu=$(ls -a "$zet" | uniq -u | fzf --height=100% --reverse --header-first)

nvim "$zet"/"$menu"
# emacsclient -c -a emacs -n "$zet"/"$menu"
