#!/bin/sh
# Using this script was the only way I found to launch the correct version of Picom with experimental backends on startup in XFCE

# picom --experimental-backends & #NOTE: This isnt working on new machine

picom &
