#!/bin/bash
# Keybind this script and a Vim scratchpad will pop up anywhere. Write and quit and the text is copied to clipboard to be pasted elsewhere. A poor mans Vim-everywhere. Relies on wayland clipboard & nerdfonts and will give notifications and sound effect on successfully copied.

tmp_file=$(mktemp)

if footclient -e nvim -c "startinsert" "$tmp_file"; then
  if wl-copy < "$tmp_file"; then
    notify-send "  Text copied to clipboard."
    paplay ~/sfx/me-too.ogg # Replace with your sound file
  else
    notify-send "󱘝  Error: Failed to copy text to clipboard."
  fi
  else
    notify-send "󰅚  Error: Neovim session failed."
fi

