#!/usr/bin/env bash
# Rofi Web searcher modified from a script originally by Distrotube
#
# Define web browser.
DMBROWSER="firefox"

# Search engines. Format must be: "engine_name - url".
# The url format must allow for the search keywords at the end of the url.
declare -a options=(
"Google - https://www.google.com/search?q="
"4get - https://4get.ca/web?s="
"Archwiki - https://wiki.archlinux.org/index.php?search="
"AUR - https://aur.archlinux.org/packages?O=0&K="
"Github - https://github.com/search?q="
"Letterboxd - https://letterboxd.com/search/"
"Reddit - https://www.reddit.com/search/?q="
"Wikipedia - https://en.wikipedia.org/wiki/"
"Youtube - https://www.youtube.com/results?search_query="
"Quit"
)

# Picking a search engine.
while [ -z "$engine" ]; do
enginelist=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i 20 -p 'Choose search engine ') || exit
engineurl=$(echo "$enginelist" | awk '{print $NF}')
engine=$(echo "$enginelist" | awk '{print $1}')
done

# Searching the chosen engine.
while [ -z "$query" ]; do
query=$(rofi -dmenu -i 20 -p "Searching $engine ") || exit
done

# Display search results in web browser
$DMBROWSER "$engineurl""$query"
