#! /usr/bin/env bash
# Creates a new fleeting note in my inbox with appropriate time stamping in the file name 

set -e

ZROOT=${ZET_ROOT:=~/org/roam/fleeting/}
timestamp=$(date +"%Y%m%d%H%M")
title="$timestamp" # Use timestamp as title
name="$ZROOT/$timestamp"
content="#+title: $title \n#+filetags: fleeting\n"

for word in "${@:1}"; do # changed to start at 1 to include all arguments.
    name+="--$word"
    content+=" ${word^}"
done

if [ ! -e "$name.org" ]; then
    echo -e "$content\n" > "$name.org"
fi

footclient -e nvim -n "$name.org"
